/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsNewRouteImport } from './routes/reservations.new'
import { Route as ReservationsIdRouteImport } from './routes/reservations.$id'
import { Route as InternalDashboardRouteImport } from './routes/internal.dashboard'
import { Route as InternalReservationsNewRouteImport } from './routes/internal.reservations.new'
import { Route as InternalReservationsIdRouteImport } from './routes/internal.reservations.$id'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsNewRoute = ReservationsNewRouteImport.update({
  id: '/reservations/new',
  path: '/reservations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIdRoute = ReservationsIdRouteImport.update({
  id: '/reservations/$id',
  path: '/reservations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalDashboardRoute = InternalDashboardRouteImport.update({
  id: '/internal/dashboard',
  path: '/internal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalReservationsNewRoute = InternalReservationsNewRouteImport.update({
  id: '/internal/reservations/new',
  path: '/internal/reservations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalReservationsIdRoute = InternalReservationsIdRouteImport.update({
  id: '/internal/reservations/$id',
  path: '/internal/reservations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/internal/dashboard': typeof InternalDashboardRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/internal/reservations/$id': typeof InternalReservationsIdRoute
  '/internal/reservations/new': typeof InternalReservationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/internal/dashboard': typeof InternalDashboardRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/internal/reservations/$id': typeof InternalReservationsIdRoute
  '/internal/reservations/new': typeof InternalReservationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/internal/dashboard': typeof InternalDashboardRoute
  '/reservations/$id': typeof ReservationsIdRoute
  '/reservations/new': typeof ReservationsNewRoute
  '/internal/reservations/$id': typeof InternalReservationsIdRoute
  '/internal/reservations/new': typeof InternalReservationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/signin'
    | '/internal/dashboard'
    | '/reservations/$id'
    | '/reservations/new'
    | '/internal/reservations/$id'
    | '/internal/reservations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/signin'
    | '/internal/dashboard'
    | '/reservations/$id'
    | '/reservations/new'
    | '/internal/reservations/$id'
    | '/internal/reservations/new'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendar'
    | '/dashboard'
    | '/signin'
    | '/internal/dashboard'
    | '/reservations/$id'
    | '/reservations/new'
    | '/internal/reservations/$id'
    | '/internal/reservations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  InternalDashboardRoute: typeof InternalDashboardRoute
  ReservationsIdRoute: typeof ReservationsIdRoute
  ReservationsNewRoute: typeof ReservationsNewRoute
  InternalReservationsIdRoute: typeof InternalReservationsIdRoute
  InternalReservationsNewRoute: typeof InternalReservationsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/new': {
      id: '/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof ReservationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/$id': {
      id: '/reservations/$id'
      path: '/reservations/$id'
      fullPath: '/reservations/$id'
      preLoaderRoute: typeof ReservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/dashboard': {
      id: '/internal/dashboard'
      path: '/internal/dashboard'
      fullPath: '/internal/dashboard'
      preLoaderRoute: typeof InternalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/reservations/new': {
      id: '/internal/reservations/new'
      path: '/internal/reservations/new'
      fullPath: '/internal/reservations/new'
      preLoaderRoute: typeof InternalReservationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal/reservations/$id': {
      id: '/internal/reservations/$id'
      path: '/internal/reservations/$id'
      fullPath: '/internal/reservations/$id'
      preLoaderRoute: typeof InternalReservationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  InternalDashboardRoute: InternalDashboardRoute,
  ReservationsIdRoute: ReservationsIdRoute,
  ReservationsNewRoute: ReservationsNewRoute,
  InternalReservationsIdRoute: InternalReservationsIdRoute,
  InternalReservationsNewRoute: InternalReservationsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
